### PR TITLE
Home page#001

### PR DESCRIPTION
**Pull request by Salim-54**
#### What does this PR do?

As a user, I should be able to see
- Services section
- Skills section
- About-me Section
-Contact links
-Get in Touch form

#### Description of Task to be completed? 

- User can be able to see services that I offer
- User can be able to see my skills
- User can be able to see skills
- User can be able to see My welcome speech about me
- User can be able to see skills all contact links of my social platforms
- User can be able to fill out a query form.

#### How should this be manually tested?

- Clone the repo

- checkout to branch ``HomePage#001``

- Pull changes by running `git pull`

#### Any background context you want to provide?

 N/A

#### What are the relevant Pivotal Tracker/trello stories?

- https://trello.com/c/zGoomS16/18-homepage001

#### Screenshots (if appropriate)
- Servises section
 
Screenshot (238)

- Skills section
Screenshot (239)

- About me section

Screenshot (240)

- Get in touch section

Screenshot (241)

#### Questions:

 N/A

### CODE REVIEW

**Review by PrinceNiyonshuti — APPROVED** [review]
great job you did there 🥳

**Review by Xldivin — APPROVED** [review]
looks interesting!

**Comment by Aristide123-ai** [comment]
Great work there Salim.

**Comment by Salim-54** [comment]
> Great work there Salim.

**Review by arthurjunior250 — COMMENTED** [review]
good job

**Pull request merged**
